# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-probe',
                'doc_host': 'https://arikru.github.io',
                'git_url': 'https://github.com/arikru/nbdev-probe',
                'lib_path': 'nbdev_probe'},
  'syms': {'nbdev_probe.core': {'nbdev_probe.core.foo': ('core.html#foo', 'nbdev_probe/core.py')}}}
