"""A new description"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_base.ipynb.

# %% auto 0
__all__ = ['foo', 'say_bye']

# %% ../nbs/00_base.ipynb 3
def foo(): pass

# %% ../nbs/00_base.ipynb 4
def say_bye(to):
    'Say bye to somebody!!'
    return f'Bye {to}!'
